services:
  {{project-name}}:
    image: registry.rwx.cat/{{project-name}}:latest
    container_name: {{project-name}}
    ports:
      - "{{default_port}}:{{default_port}}"
    environment:
      - RUN_MODE=prod
    pull_policy: always
    restart: always
